### ISSUE TITLE
Are you planning to release mocap_msgs into rosdistro?

### ISSUE THREAD

**Issue by pariaspe** [MOCAP4ROS2-Project/mocap_msgs#11]
Hi, I would like to know if you are planning to add `mocap_msgs` to [rosdistro](https://github.com/ros/rosdistro).
We are integrating mocap4ros2 project into aerostack2 (see https://github.com/aerostack2/aerostack2/pull/349) but our CI checks fails because the dependency `mocap_msgs` is not found.
Thanks in advance!

**Comment by jmguerreroh** [comment]
Answered https://github.com/aerostack2/aerostack2/pull/349#issuecomment-1828603744
