### ISSUE TITLE
Clean messages

### ISSUE THREAD

**Issue by fmrico** [MOCAP4ROS2-Project/mocap_msgs#5]
Hi @lbajo 

I was about to release the package when I saw some issues that must be fixed before:
* What are these services? Are they really used? Are they dependant on a specific vendor (Vicon)? I would remove it.
* Why Markers and MarkersWithId. I would unify...
* `Control.msg` is particular of mocap4ros2. I would create a `mocap4ros2_msgs` package in https://github.com/MOCAP4ROS2-Project/mocap4ros2_core.

I want to resolve this ASAP, in order to release the package.

**Comment by lbajo** [comment]
Hello @fmrico,

-  The services are not currently being used, I think they were used initially but now their function is performed through the Vicon SDK.
-  The MarkersWithId were initially created for Qualisys but currently I think "normal" Markers are used, if we remove them it wouldn't pose any problem in my opinion.
-  The other mocap_msg messages are only used for vicon as well, in my opinion it's not a good idea to separate them.
